services:
  printscript-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - .env
    environment:
      - VITE_SNIPPET_RUNNER_URL=${SNIPPET_RUNNER_URL}
      - VITE_SNIPPET_OPERATIONS_URL=${SNIPPET_OPERATIONS_URL}
      - VITE_FRONTEND_URL=${FRONTEND_URL}
      - VITE_AUTH0_USERNAME=${AUTH0_USERNAME}
      - VITE_AUTH0_PASSWORD=${AUTH0_PASSWORD}
      - VITE_AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - VITE_AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}

