FROM node:20-slim AS build

WORKDIR /app

COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json

RUN npm ci

COPY . /app

ARG SNIPPET_RUNNER_URL
ARG SNIPPET_OPERATIONS_URL
ARG FRONTEND_URL
ARG AUTH0_USERNAME
ARG AUTH0_PASSWORD
ARG AUTH0_DOMAIN
ARG AUTH0_CLIENT_ID
ARG AUTH0_AUDIENCE

ENV VITE_SNIPPET_RUNNER_URL=$SNIPPET_RUNNER_URL
ENV VITE_SNIPPET_OPERATIONS_URL=$SNIPPET_OPERATIONS_URL
ENV VITE_FRONTEND_URL=$FRONTEND_URL
ENV VITE_AUTH0_USERNAME=$AUTH0_USERNAME
ENV VITE_AUTH0_PASSWORD=$AUTH0_PASSWORD
ENV VITE_AUTH0_DOMAIN=$AUTH0_DOMAIN
ENV VITE_AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID
ENV VITE_AUTH0_AUDIENCE=$AUTH0_AUDIENCE


RUN npm run build

FROM nginx:alpine

COPY --from=build /app/.nginx/nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY --from=build /app/dist .

ENTRYPOINT ["nginx", "-g", "daemon off;"]