FROM node:lts-alpine3.14 as build
RUN mkdir /app
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .

ARG SNIPPET_RUNNER_URL
ARG SNIPPET_OPERATIONS_URL
ARG FRONTEND_URL
ARG AUTH0_USERNAME
ARG AUTH0_PASSWORD
ARG AUTH0_DOMAIN
ARG AUTH0_CLIENT_ID
ARG AUTH0_AUDIENCE

ENV VITE_SNIPPET_RUNNER_URL=$SNIPPET_RUNNER_URL
ENV VITE_SNIPPET_OPERATIONS_URL=$SNIPPET_OPERATIONS_URL
ENV VITE_FRONTEND_URL=$FRONTEND_URL
ENV VITE_AUTH0_USERNAME=$AUTH0_USERNAME
ENV VITE_AUTH0_PASSWORD=$AUTH0_PASSWORD
ENV VITE_AUTH0_DOMAIN=$AUTH0_DOMAIN
ENV VITE_AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID
ENV VITE_AUTH0_AUDIENCE=$AUTH0_AUDIENCE

RUN npm run build



FROM node:lts-alpine3.14 as production
WORKDIR /app
COPY --from=build /app/dist /app/dist
COPY package.json .
COPY vite.config.ts .
RUN npm install --production
RUN npm install vite
EXPOSE 5173
CMD ["npm", "run", "preview"]